name: Sync Fork

on:
  schedule:
    - cron: '0 2 * * *'  # Tous les jours à 02:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Nécessaire pour git merge

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/microsoft/vscode-pull-request-github
          git fetch upstream

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Merge upstream/main into fork/main
        run: |
          git checkout main
          git merge upstream/main
          git push origin main
